In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, roc_auc_score, roc_curve, accuracy_score, classification_report, confusion_matrix
from tensorflow import keras
#import cv2



In [23]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [12]:
x_train.shape,x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [27]:
x_train[0]

numpy.ndarray

In [19]:
x_train = x_train/255.0
x_test = x_test/255.0

In [20]:
#sklearn expects i/p to be 2d array-model.fit(x_train,y_train)=>reshape to
#2d array
nsamples, nx, ny, nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))

In [21]:
##so,eventually,model.predict() should also be a 2d input
nsamples, nx, ny, nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

In [30]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [29]:
x_train2

array([[0.23137255, 0.24313725, 0.24705882, ..., 0.48235294, 0.36078431,
        0.28235294],
       [0.60392157, 0.69411765, 0.73333333, ..., 0.56078431, 0.52156863,
        0.56470588],
       [1.        , 1.        , 1.        , ..., 0.31372549, 0.3372549 ,
        0.32941176],
       ...,
       [0.1372549 , 0.69803922, 0.92156863, ..., 0.04705882, 0.12156863,
        0.19607843],
       [0.74117647, 0.82745098, 0.94117647, ..., 0.76470588, 0.74509804,
        0.67058824],
       [0.89803922, 0.89803922, 0.9372549 , ..., 0.63921569, 0.63921569,
        0.63137255]])

In [8]:
model=RandomForestClassifier()

In [28]:
model.fit(x_train2,y_train)

c:\Users\Dr. Emilia Boehm\DataScienceCourseSpiced\Capstone\.venv\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [ ]:
y_pred=model.predict(x_test2)
y_pred

array([2, 8, 8, ..., 5, 5, 7], dtype=uint8)

In [ ]:
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.56      0.54      0.55      1038
           1       0.54      0.52      0.53      1046
           2       0.33      0.38      0.35       869
           3       0.27      0.34      0.30       796
           4       0.41      0.40      0.40      1006
           5       0.38      0.41      0.40       924
           6       0.55      0.45      0.50      1230
           7       0.46      0.52      0.48       889
           8       0.62      0.59      0.60      1056
           9       0.56      0.48      0.52      1146

    accuracy                           0.47     10000
   macro avg       0.47      0.46      0.46     10000
weighted avg       0.48      0.47      0.47     10000



In [ ]:
confusion_matrix(y_pred,y_test)

array([[563,  34, 102,  50,  57,  28,  11,  55,  89,  49],
       [ 36, 541,  45,  48,  28,  32,  31,  43,  85, 157],
       [ 57,  21, 326,  86, 120,  91,  89,  46,  17,  16],
       [ 16,  37,  84, 271,  40, 155,  74,  55,  28,  36],
       [ 32,  17, 152,  72, 406,  83, 115,  91,  18,  20],
       [ 19,  29,  66, 182,  56, 382,  53,  84,  30,  23],
       [ 21,  50, 112, 140, 154,  90, 553,  63,  15,  32],
       [ 29,  32,  61,  61,  94,  78,  24, 458,  21,  31],
       [169,  64,  23,  22,  26,  24,   9,  17, 621,  81],
       [ 58, 175,  29,  68,  19,  37,  41,  88,  76, 555]], dtype=int64)